### ISSUE TITLE
where is the data?

### ISSUE THREAD

**Issue by gs55** [p2irc/deepplantphenomics#13]
I tried `python  cifar10_test.py`  , then I had an error as follows.

` No such file or directory: './data/cifar10/train/train.txt'`

where is the data?

**Comment by jubbens** [comment]
The CIFAR10 dataset is not included in the repo, but can be downloaded using [nvidia DIGITS](https://github.com/NVIDIA/DIGITS/blob/master/docs/StandardDatasets.md#cifar10).

**Comment by gs55** [comment]
Thank you for ansering.

One more question, in PlantCV_segmentation_test.py  it says that
`# Load all VIS images from a Lemnatec image repository
model.load_lemnatec_images_from_directory('./data')`

Could you tell me the URL of Lemnatec image download site ?

**Comment by jubbens** [comment]
@gs55 that loader is meant for any dataset collected on a Lemnatec system, not any specific dataset. The package does not include a dataset of that type.
