### ISSUE TITLE
set_learning_rate_decay

### ISSUE THREAD

**Issue by 3nryk** [p2irc/deepplantphenomics#24]
Hi!

I'm having an error when doing model.set_learning_rate_decay() after model.load_multiple_labels_from_csv().

self.__total_training_samples is set to 0 and is only changed when we do model.begin_training().
![image](https://user-images.githubusercontent.com/8448556/62401250-99d5bf00-b53f-11e9-9b60-5c8b7363f406.png)

Thank you!

**Comment by jubbens** [comment]
Fixed in 0c55eb5. Thanks @donovanlavoie !
